doctor/urls.py
from django.urls import path
from .import views

app_name='doctor'

urlpatterns =[
    path('home',views.home,name='home'),
    path('master',views.master,name='master'),
    path('logout',views.logout,name='logout'),
    path('patients',views.patients,name='patients'),
    path('patient/records',views.records,name='records'),
    path('appoinments',views.appoinments,name='appoinments'),
    path('prescription/<int:booking_id>',views.prescription,name='prescription'),
    path('discharge/request',views.discharge_req,name='discharge_request'),
    path('patient/profile/<int:bid>',views.patient_profile,name='patient_profile'),
    path('change/password',views.change_password,name='change_password'),
    
     
    
    
        
    
    
    
    
]

myhospital/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myhospital_app.urls')),
    path('admin_app/',include('admin_app.urls')),
    path('doctor/',include('doctor.urls')),
    path('staff/',include('staff.urls')),
    path('patient/',include('patient.urls')),
    
    
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

patient/urls.py
from django.urls import path
from .import views
 

app_name='patient'

urlpatterns =[
    path('master',views.master,name='master'),
    path('home',views.home,name='home'),
    path('appoinments',views.appoinments,name='appoinments'),
    path('logout',views.logout,name='logout'),
    path('new/booking',views.new_booking,name='new_booking'),
    path('appoinment/list',views.appoinment_list,name='appoinment_list'),
    path('change/password',views.change_password,name='change_password'),
    path('prescriptions',views.prescriptions,name='prescriptions'),
    path('view/prescriptions/<int:bid>',views.view_prescription,name='view_prescriptions'),
    
    
    
    
    ]

staff/urls.py
from django.urls import path
from .import views

app_name='staff'

urlpatterns =[
    path('master',views.master,name='master'),
    path('home',views.home,name='home'),
    path('patients',views.patients,name='patients'),
    path('appoinments',views.appoinments,name='appoinments'),
    path('logout',views.logout,name='logout'),
    
    
    
    
    
]

doctor/models.py
from django.db import models

from admin_app.models import Departments


import random
# Create your models here.

class Doctor(models.Model):
    name = models.CharField(max_length=30)
    age= models.CharField(max_length=30)
    department = models.ForeignKey(Departments, on_delete = models.CASCADE,default=0)
    qualification = models.CharField(max_length=100)
    doctorid = models.CharField(max_length=30)
    password = models.CharField(max_length=30,default='12345678')
    email = models.CharField(max_length=30)
    mobile = models.BigIntegerField(default=1)
    image = models.ImageField(upload_to = 'doctor')
    address = models.CharField(max_length=100,default='')
    status = models.CharField(max_length=10,default='active')
    

    class Meta:
        db_table = 'doctor_tb'
        

patient/models.py
from django.db import models
from doctor .models import Doctor

# Create your models here.


class Slots(models.Model):
    doctor = models.ForeignKey(Doctor,on_delete=models.CASCADE)
    day = models.CharField(max_length=20)
    time = models.CharField(max_length=20)
    status = models.CharField(max_length=20,default='available')
    
    class Meta:
        db_table = 'slots_tb'

doctor/views.py
from django.shortcuts import render,redirect
from .models import Doctor
from django.db.models import F
from myhospital_app.models import Patient,Booking,Prescription


# Create your views here.

def home(request):

    doctors = Doctor.objects.get(id= request.session['doctor'])
    noofpatient= Booking.objects.filter(doctor = request.session['doctor']).count
    return render(request,'doctor/home.html',{'doctor':doctors,'count':noofpatient})

def master(request):
    doctors = Doctor.objects.get(id= request.session['doctor'])
    return render(request,'doctor/master.html',{'doctor':doctors})

def logout(request):
    del request.session['doctor']
    request.session.flush()
    return redirect( 'myhospital_app:home' )

def patients(request):
    return render(request,'doctor/patients.html')

def records(request):
    booking=Booking.objects.filter(doctor = request.session['doctor'],status='consulted')
    return render(request,'doctor/patient_records.html',{'booking':booking})

def appoinments(request):
    bookings = Booking.objects.filter(doctor = request.session['doctor'])
    
    return render(request,'doctor/appoinments.html',{'bookings':bookings})

 

def prescription(request ,booking_id):
    msg=''
    bookings = Booking.objects.get(id = booking_id)
    
    if request.method == 'POST':
        diagnosis = request.POST['diagnosis']
        medicine = request.POST['medicine']
        dosage = request.POST['dosage']
        frequency = request.POST['frequency']
        prescription = Prescription(
            diagnosis=diagnosis,
            medication_name=medicine,
            dosage=dosage,
            frequency=frequency,
            booking= bookings
        )
        prescription.status='consulted'
        
        prescription.save()
        bookings.status='consulted'
        bookings.save()
        msg='Prescription Added successfully'
        
        
    return render(request,'doctor/prescription.html',{'bookings':bookings,'msg':msg})




def discharge_req(request):
    return render(request,'doctor/discharge_request.html')

def patient_profile(request,bid):
    booking=Booking.objects.get(id=bid)
    print(booking)
    prescription = Prescription.objects.get(booking_id=booking)
    print("*************",prescription.id)
    return render(request,'doctor/patient_profile.html',{'booking':booking,'prescription':prescription})



def change_password(request):
    msg = ''
    if request.method == 'POST':
        current_password = request.POST['current_password']
        new_password = request.POST['new_password']
        confirm_password = request.POST['confirm_password']

        if new_password == confirm_password:
            
            if len(new_password) >= 8:


                doctor = Doctor.objects.get(id= request.session['doctor'])

                if doctor.password == current_password:

                    Doctor.objects.filter(id= request.session['doctor']).update(password = confirm_password)
                    
                    msg = 'Password changed succesfully'
                else:
                    msg = 'Invalid password'
            else:
                msg = 'password should be min 8 characters'
        else:
            msg = 'password does not match'

    return render(request,'doctor/change_password.html',{'msg':msg})

 

patient/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse
from django.conf import settings
from django.core.mail import send_mail
from django.core.exceptions import ValidationError  

from myhospital_app .models import Booking , Patient
from admin_app .models import Departments
from doctor.models import Doctor
from .models import Slots

# Create your views here.

def master(request):
    # patient = Patient.objects.filter(id = request.session['patient']).values('name')
    
    patient = Patient.objects.get(id = request.session['patient'])
     
    return render(request,'patient/master.html' , {'patient':patient})

def home(request):
    patient = Patient.objects.get(id = request.session['patient'])

    patient_id = request.session['patient']
    
     
    
    recent_booking = Booking.objects.filter(patient_id=patient_id).order_by('-id')[0:1]
    
    return render(request,'patient/home.html',{'booking':recent_booking,'patient':patient})

 

def appoinments(request):
    patient = Patient.objects.get(id = request.session['patient'])
    
    return render(request,'patient/appoinments.html',{'patient':patient})

def logout(request):
    del request.session['patient']
    request.session.flush()
    return redirect( 'myhospital_app:home')

 
def new_booking(request):
    patient = Patient.objects.get(id = request.session['patient'])
    doctor = Doctor.objects.all()
    departments = Departments.objects.all()
    slots = Slots.objects.all()
    msg = ''
    mail=''
    if request.method =='POST':
        patient_name = request.POST['name']
        patient_age = request.POST['age']
        gender = request.POST['gender']
        phone = request.POST['phone']
        email = request.POST['email']
        selected_department = request.POST['department']
        selected_doctor = request.POST['doctor']
        slot_day = request.POST['day-select']
        slot_time = request.POST['time-select']
        patientId = request.POST['patientId']
        
        booking = Booking(
            name = patient_name,
            age = patient_age,
            gender = gender,
            phone = phone,
            email = email,
            department_id = selected_department,
            doctor_id = selected_doctor,
            slot_id = slot_day,
            slotTime = slot_time,
            patient_id=patientId,
             
        )
        booking.save() 
        msg='Appoinment registered succesfully'
        mail='Your Appoinment for the day '+str(slot_day)+ ' in MyHospital with '+selected_doctor+' at '+str(slot_time)+  ' has been Registered Successfully'
        msg ='Registered Successfully'
        send_mail(
            'Welcome to MyHospital ' ,
            mail,
            settings.EMAIL_HOST_USER,
            [booking.email]
        )
        
    else:
        msg='Appoinment Not done'
        
    return render(request,'patient/new_booking.html',{'doctor':doctor,'departments':departments,'slots':slots,'patient':patient})
 
 
 
def appoinment_list(request):
    # getting the logged in patients id 
    
    patient_id = request.session['patient']
    
    bookings = Booking.objects.filter(patient_id=patient_id)
     
    return render(request,'patient/appoinment_list.html',{'bookings':bookings})

def change_password(request):
    msg = ''
    if request.method == 'POST':
        current_password = request.POST['current_password']
        new_password = request.POST['new_password']
        confirm_password = request.POST['confirm_password']

        if new_password == confirm_password:
            
            if len(new_password) >= 8:


                patient = Patient.objects.get(id= request.session['patient'])

                if patient.password == current_password:

                    Patient.objects.filter(id= request.session['patient']).update(password = confirm_password)
                    
                    msg = 'Password changed succesfully'
                else:
                    msg = 'Invalid password'
            else:
                msg = 'password should be min 8 characters'
        else:
            msg = 'password does not match'

    return render(request,'patient/change_password.html',{'msg':msg})


def prescriptions(request):
    patient_id= request.session['patient']
    bookings = Booking.objects.filter(patient_id=patient_id)
    
    return render(request,'patient/prescriptions.html',{'booking':bookings})

def view_prescription(request,bid):
    booking = Booking.objects.get(id = bid)
    
    return redirect('patient:appoinment_list')

doctor/templates/doctor/appoinments.html
{% extends "doctor/master.html" %}
{% load static %}
{% block header %}
<style>
    table {
        width: 100%;
        border-collapse: collapse;
        
      }
      
      th, td {
         
        padding: 8px;
        text-align: left;
        border-bottom: 1px solid #ddd;
      }
      
      th {
        background-color: #f2f2f2;
      }
      
      tr:hover {
        background-color: #f5f5f5;
      }
      .doc-rec{
        padding-top: 50px;
      }

</style>

{% endblock %}



{% block content %}

 
<div class="container-fluid doc-rec">
    

    <table>
        <tr>
          <th>Name</th>
          <th>Age</th>
          <th>Email</th>
          <th>Mobile</th>
          <th>Appoinment Date</th>
          <th>Time</th>
          <th>Status</th>
          <th></th>
           
          
        </tr>
        {% for i in bookings %} 
        <tr>
          <td>{{i.name}}</td>
          <td>{{i.age}}</td>
          <td>{{i.email}}</td>
          <td>{{i.phone}}</td>
          <td>{{i.slot.day}}</td>
          <td>{{i.slot.time}}</td>
          <td>{{i.status}}</td>
          <td><a href="{% url 'doctor:prescription' i.id %}">View</a></td>
          
           
           
    
        </tr>
        {% endfor %}
         
      </table>
    </div>
    
 

{% endblock %}

doctor/templates/doctor/change_password.html
{% extends "doctor/master.html" %}
{% load static %}
{% block header %}
<style>
	form {
		display: flex;
		flex-direction: column;
		align-items: center;

		margin-top: 50px;
	}

	.form {
		display: flex;
		flex-direction: column;
		align-items: center;
	}

	input[type=text],input[type=password],input[type=file],select {
		margin: 10px;
		padding: 10px;
		width: 500px;
		border-radius: 5px;
		border: 1px solid #ccc;
	}

	input[type=submit] {
		background-color: #4CAF50;
		color: white;
		border: none;
		padding: 10px 20px;
		text-align: center;
		text-decoration: none;
		display: inline-block;
		font-size: 16px;
		margin: 10px;
		border-radius: 5px;
		cursor: pointer; 
	}

	label {
		margin: 10px;
	}

	.signup {
		text-align: center;
	}

</style>


{% endblock %}



{% block content %}



<div class="container-fluid form">
	<div class="" style="text-align: center; margin-top: 20px; margin-bottom: 20px;">
		<h3>Change Password</h3>
	</div>
	<table>
		{{ msg }}



		<form action="" method="POST" enctype="multipart/form-data">
			{% csrf_token %}

			<tr>
				<td><label for="old_password">Current Password :</label></td>
				<td><input type="text" id="old_password" name="current_password" required></td>
			</tr>

			<tr>
				<td><label for="new password">New Password :</label></td>
				<td><input type="password" name="new_password" required></td>
			</tr>

            <tr>
				<td><label for="Confirm Password">Confirm Password :</label></td>
				<td><input type="password" name="confirm_password" required></td>
			</tr>
            <tr>
				<td></td>
				<td><input type="submit" value="Submit"></td>
			</tr>

        </form>
    </table>
</div>

{% endblock %}

doctor/templates/doctor/discharge_request.html
{% extends "doctor/master.html" %}
{% load static %}
{% block header %}
<style>
    table {
        width: 100%;
        border-collapse: collapse;
        
      }
      
      th, td {
         
        padding: 8px;
        text-align: left;
        border-bottom: 1px solid #ddd;
      }
      
      th {
        background-color: #f2f2f2;
      }
      
      tr:hover {
        background-color: #f5f5f5;
      }
      .doc-rec{
        padding-top: 50px;
      }

</style>

{% endblock %}



{% block content %}

 
<div class="container-fluid doc-rec">
  <table>
      <tr>
        <th>Name</th>
        <th>Age</th>
        <th>Email</th>
        <th>Mobile</th>
        <th></th>
         
      </tr>
       
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td><button type="button" class="btn btn-primary">Primary</button></td>
         
  
      </tr>
       
    </table>
  </div>
    
 

{% endblock %}

doctor/templates/doctor/home.html
{% extends "doctor/master.html" %}
{% load static %}
{% block header %}
<link rel="stylesheet" href="{% static 'css/homepage.css' %}">


{% endblock %}



{% block content %}


<section class="main-section">


    <div class="profile-section">
        <div class="top-section">
            <div class="profile-image">
                <img src="{% static 'image/doctor.png' %}" alt="" width="70%" class="img">
            </div>
            <div class="profile-details">
                <h3>Dr {{doctor.name |title}}</h3>
                <h4> {{doctor.department.name|title}}</h4>
            </div>
        </div>

        <div class="bottom-section">

            <table>
                <tr>
                    <td>
                        <h5>Age :</h5>
                    </td>
                    <td>
                        <h5>{{doctor.age}}</h5>
                    </td>
                </tr>
                <tr>
                    <td>
                        <h5>Mobile :</h5>
                    </td>
                    <td>
                        <h5>{{doctor.mobile}}</h5>
                    </td>
                </tr>
                <tr>
                    <td>
                        <h5>Email :</h5>
                    </td>
                    <td>
                        <h5>{{doctor.email}}</h5>
                    </td>
                </tr>
                
                <tr>
                    <td>
                        <h5>Adress :</h5>
                    </td>
                    <td>
                        <h5>Hi villa, Calicut</h5>
                    </td>

                </tr>
                <tr>

                    <td>
                        <h5>Qualification :</h5>
                    </td>
                    <td>
                        <h5>{{doctor.qualification|title}}</h5>
                    </td>
                </tr>
                
                
                
            </table>

            <div class="bottom-child">

            </div>


        </div>
    </div>


    <div class="info-section">

        <div class="info-top">

            <div class="info-cards">
                <div class="cards-img"><i class="las la-user-injured" style="font-size: 80px;"></i></div>
                <div class="cards-content"><h3>Patients</h3> <h3>{{count}}</h3></div>
            </div>
            <div class="info-cards">
                <div class="cards-img"> <i class="las la-calendar-check" style="font-size: 80px;"></i></div>
                <div class="cards-content"><h3>Appoinments</h3><h3>{{count}}</h3></div>
            </div>

        </div>

    </div>

</section>


{% endblock %}

doctor/templates/doctor/master.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css">

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>

  <link rel="stylesheet" href="{% static 'css/masterpage.css' %}">

  <link rel="stylesheet"
    href="https://maxst.icons8.com/vue-static/landings/line-awesome/font-awesome-line-awesome/css/all.min.css">

  <link rel="stylesheet"
    href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">

  {% block header %}

  {% endblock %}
</head>


<body>
  <div class="container-fluid maindiv">

    <!-- header  -->

    <div class="row container-fluid">
      <div class="col-sm-2 dashboard1">
        <div class=" "><img src="{{doctor.image.url}}" alt="" width="60px" class="profile">
          <br>
          <h3></h3>
        </div>
        

      </div>


      <div class="col-sm-10 navbarr">

        <a href="">
          <div class="nav-items"></div>
        </a>


        <div class="nav-items " data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@mdo"><img
            src="{% static 'image/logo.png' %}" alt="" width="60px" class=""></div>

      </div>
    </div>


    <div class="row container-fluid">
      <div class=" col-sm-2 dashboard2">

        <div class="" style="color: white;"><h4>{{doctor.name}}</h4></div>

        <a href="{% url 'doctor:home' %}">
          <div class="dash1 "><i class="las la-igloo">Dashboard</i></div>
        </a>
        <a href="{% url 'doctor:patients' %}">
          <div class="dash-elements"><i class="las la-user-injured"> Patients</i></div>
        </a>
        <a href="{% url 'doctor:appoinments' %}">
          <div class="dash-elements"> <i class="las la-calendar-check">Appoinments</i></div>
        </a>
        <a href="{% url 'doctor:change_password' %}">
          <div class="dash-elements"> <i class="las la-calendar-check">Change Password</i></div>
        </a>
         
         
        <div class="logout"><a href="{% url 'doctor:logout' %}"><button type="button" class="btn btn-danger"> logout</button></a></div>



      </div>











      <div class="col-sm-10 content">
        {% block content %}


        {% endblock %}

      </div>
    </div>
  </div>


</body>

</html>

doctor/templates/doctor/patient_profile.html
{% extends "doctor/master.html" %}
{% load static %}
{% block header %}
<style>
  table {
    width: 100%;
    border-collapse: collapse;

  }

  th,
  td {

    padding: 8px;
    text-align: left;
    border-bottom: 1px solid #ddd;
  }

  th {
    background-color: #f2f2f2;
  }


  .doc-rec {
    padding-top: 50px;
  }

  .report,
  .medicine {
    width: 500px;
    height: 100px;
    border: black 1px;
    display: flex;

  }
</style>

{% endblock %}



{% block content %}



<div class="mb-3">
  <table>
    <tr>
      <th>Name :</th>

      <td>{{booking.name |title}}</td>
      <th>Age :</th>
      <td>{{booking.age}}</td>
    </tr>
    <tr>
      <th>DOB :</th>
      <td>{{booking.dob}}</td>
      <th>Place</th>
      <td>{{booking.phone |title}}</td>
    </tr>
  </table>
</div>
<form action="" method="POST">
  {% csrf_token %}

  <div class="mb-3 report">

    <h6>Report :</h6> {{prescription.diagnosis}}
  </div>
  <div class="mb-3 medicine">
    <h6>Medicine :</h6> {{prescription.medication_name}}
  </div>
   
</form>
{% endblock %}

doctor/templates/doctor/patient_records.html
{% extends "doctor/master.html" %}
{% load static %}
{% block header %}
<style>

    table {
        width: 100%;
        border-collapse: collapse;
        
      }
      
      th, td {
         
        padding: 8px;
        text-align: left;
        border-bottom: 1px solid #ddd;
      }
      
      th {
        background-color: #f2f2f2;
      }
      
      tr:hover {
        background-color: #f5f5f5;
      }
      .doc-rec{
        padding-top: 50px;
      }

</style>

{% endblock %}



{% block content %}
  
<div class="container-fluid doc-rec">
    <table>
        <tr>
          <th>Name</th>
          <th>Age</th>
          <th>Mobile</th>
          <th>Place</th>
          <th>Status</th>
           <th></th>
          
           
        </tr>
      {% for i in booking %}
        <tr>
          <td>{{i.name |title}}</td>
          <td>{{i.age}}</td>
          <td>{{i.phone}}</td>
          <td>{{i.place |title}}</td>
          <td>{{i.status |title}}</td>
           <td><a href="{% url 'doctor:patient_profile' i.id %}">View</a></td>
           
    
        </tr>
        {% endfor %}
         
      </table>
    </div>

{% endblock %}

doctor/templates/doctor/patients.html
{% extends "doctor/master.html" %}
{% load static %}
{% block header %}
<style>



</style>

{% endblock %}



{% block content %}

<div class="container-fluid doctor-cards  ">
     

    

   

    <a href="{% url 'doctor:records' %}">
        <div class="card cards mb-3 " style="max-width: 340px; max-height:200px;">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src=" https://cdn.icon-icons.com/icons2/2266/PNG/512/crowd_patient_patients_icon_140474.png"
                        class="img-fluid rounded-start" alt="...">
                </div>
                <div class="col-md-8 ">
                    <div class="card-body">
                        <h2 class="card-title">Patient Records</h2>
                        
                    </div>
                </div>
            </div>
        </div>
    </a>

    <a href="{% url 'doctor:discharge_request' %}">
        <div class="card cards mb-3" style="max-width: 340px; max-height:200px;">
            <div class="row g-0 card3">
                <div class="col-md-4">
                    <img src="https://thumbs.dreamstime.com/b/discharge-icon-discharge-release-276477125.jpg"
                        class="img-fluid rounded-start" alt="...">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h2 class="card-title">Discharge Request</h2>
    
    
                    </div>
                </div>
            </div>
        </div>
    </a>


</div>

{% endblock %}

doctor/templates/doctor/prescription.html
{% extends "doctor/master.html" %}
{% load static %}
{% block header %}
<style>
  table {
    width: 100%;
    border-collapse: collapse;

  }

  th,
  td {

    padding: 8px;
    text-align: left;
    border-bottom: 1px solid #ddd;
  }

  th {
    background-color: #f2f2f2;
  }


  .doc-rec {
    padding-top: 50px;
  }

  input[type=text],
  input[type=password],
  input[type=file],
  input[type=date],
  input[type=number],
  select {
    margin: 10px;
    padding: 10px;
    width: 80px;
    border-radius: 5px;
    border: 1px solid #ccc;
  }
  button{
    
    display: inline-block;
    outline: 0;
    border: none;
    cursor: pointer;
    font-weight: 600;
    border-radius: 4px;
    font-size: 13px;
    height: 30px;
    background-color: #0000000d;
    color: #0e0e10;
    padding: 0 20px;
    

  }
</style>

{% endblock %}



{% block content %}



<div class="mb-3">
  <table>
    <tr>
      <th>Name :</th>

      <td>{{bookings.name |title}}</td>
      <th>Age :</th>
      <td>{{bookings.age}}</td>
    </tr>
    <tr>
      <th>Gender :</th>
      <td>{{bookings.gender}}</td>
      <th>Place</th>
      <td>{{bookings.phone |title}}</td>
    </tr>
  </table>
</div>
<form action="" method="POST">
  {% csrf_token %}

  <div class="mb-3">
    <label for="exampleFormControlTextarea1" class="form-label">Diagnosis :</label>
    <textarea class="form-control" id="" rows="4" name="diagnosis"></textarea>
  </div>
  <div class="mb-3">
    <label for="exampleFormControlTextarea1" class="form-label">Medicine :</label>
    <textarea class="form-control" id="" rows="4" name="medicine"></textarea>
  </div>
  <div class="mb-3">
    <label for="exampleFormControlTextarea1" class="form-label">Dosage :</label>
    <input type="number" name="dosage" min="1">

  </div>
  <div class="mb-3">
    <label for="exampleFormControlTextarea1" class="form-label">Frequency :</label>
    <textarea class="form-control" id="" rows="4" name="frequency"></textarea>
 

</div>
  <div class="mb-3" style="text-align: center;"><button type="submit">Add prescription</button></div>
</form>
{% endblock %}