myhospital/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myhospital_app.urls')),
    path('admin_app/',include('admin_app.urls')),
    path('doctor/',include('doctor.urls')),
    path('staff/',include('staff.urls')),
    path('patient/',include('patient.urls')),
    
    
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myhospital_app/urls.py
from django.urls import path
from .import views

 

app_name='myhospital_app'

urlpatterns =[
    path('master',views.master,name='master'),
    path('login',views.login,name='login'),
    path('booking',views.booking,name='booking'),
    path('home',views.home,name='home'),
    path('demo',views.demo,name='demo'),
    path('patient_portal',views.patient_portal,name='patient_portal'),
    path('staff_login',views.staff_login,name='staff_login'),
    path('doctor_login',views.doctor_login,name='doctor_login'),
    path('hospital/admin_login',views.admin,name='admin_login'),
    path('about_us',views.about_us,name='about_us'),
    path('contact',views.contact,name='contact'),
    path('get_doctors/', views.get_doctors, name='get_doctors'),
    path('get_day/',views.get_day,name = 'get_day'),
    path('get_time/',views.get_time,name = 'get_time'),
    path('patient_register',views.patient_register,name='patient_register'),
    
     
    

]
      

staff/urls.py
from django.urls import path
from .import views

app_name='staff'

urlpatterns =[
    path('master',views.master,name='master'),
    path('home',views.home,name='home'),
    path('patients',views.patients,name='patients'),
    path('appoinments',views.appoinments,name='appoinments'),
    path('logout',views.logout,name='logout'),
    
    
    
    
    
]

myhospital_app/models.py
from django.db import models
from admin_app.models import Departments
from doctor .models import Doctor
from patient.models import Slots




# Create your models here.





    
class Patient(models.Model):
    name = models.CharField(max_length=30)
    age  = models.CharField(max_length=10)
    dob  = models.DateField()
    gender  = models.CharField(max_length=10)
    place  = models.CharField(max_length=30)
    phone  = models.BigIntegerField()
    email  = models.CharField(max_length=30)
    status = models.CharField(max_length=10,default='pending')
    password=models.CharField(max_length=10,default='12345678')
     
    class Meta:
        db_table = 'patient_tb'
        
        
from .models import Patient


class Booking(models.Model):
    name = models.CharField(max_length=30)
    age = models.CharField(max_length=10)   
    gender = models.CharField(max_length=10)
    phone = models.BigIntegerField()
    email = models.CharField(max_length=30)
    department = models.ForeignKey(Departments, on_delete = models.CASCADE)
    doctor = models.ForeignKey(Doctor,on_delete = models.CASCADE)
    slot = models.ForeignKey(Slots,on_delete=models.CASCADE)
    slotTime = models.CharField(max_length=10)
    patient = models.ForeignKey(Patient,null=True, blank=True, on_delete=models.SET_NULL)
    status = models.CharField(max_length=20,default='pending')
    class Meta:
        db_table = 'booking_tb'
        
class Prescription(models.Model):
    diagnosis = models.CharField(max_length=200)
    medication_name = models.CharField(max_length=100)
    dosage = models.CharField(max_length=50)
    frequency = models.CharField(max_length=50)
    status = models.CharField(max_length=10 , default='active')
    booking = models.ForeignKey(Booking,on_delete = models.CASCADE)
    
    class Meta:
        db_table ='prescription_tb'

myhospital_app/views.py
from django.shortcuts import render,redirect
from admin_app .models import Admin
from doctor.models import Doctor
from django.core.mail import send_mail
from staff.models import Staff
from django.http import JsonResponse
from .models import Patient,Booking
from patient .models import Slots
from admin_app .models import Departments
from django.conf import settings
import random
from django.core.exceptions import ValidationError  
from datetime import datetime

# Create your views here.

def master(request):
    return render(request,'myhospital_app/master.html')

def login(request):
    msg = ''
    if request.method == 'POST':
        patient_id = request.POST['patient_id']
        password = request.POST['password']
        
        try:
            patient = Patient.objects.get(email=patient_id,password=password)
            request.session['patient']=patient.id
            return redirect('patient:home')
        except:
            msg= 'Incorrect Username Or Password'
    else:
        msg='error'        
    return render(request,'myhospital_app/login.html')

def booking(request):
    doctor = Doctor.objects.all()
    departments = Departments.objects.all()
    slots = Slots.objects.all()
    msg = ''
    mail=''
    if request.method =='POST':
        patient_name = request.POST['name']
        patient_age = request.POST['age']
        gender = request.POST['gender']
        phone = request.POST['phone']
        email = request.POST['email']
        selected_department = request.POST['department']
        selected_doctor = request.POST['doctor']
        slot_day = request.POST['day-select']
        slot_time = request.POST['time-select']
        
        booking = Booking(
            name = patient_name,
            age = patient_age,
            gender = gender,
            phone = phone,
            email = email,
            department_id = selected_department,
            doctor_id = selected_doctor,
            slot_id = slot_day,
            slotTime = slot_time,
             
        )
        booking.save() 
        msg='Appoinment registered succesfully'
        mail='Your Appoinment for the day '+str(slot_day)+ ' in MyHospital with '+selected_doctor+' at '+str(slot_time)+  ' has been Registered Successfully'
        msg ='Registered Successfully'
        send_mail(
            'Welcome to MyHospital ' ,
            mail,
            settings.EMAIL_HOST_USER,
            [booking.email]
        )
        
    else:
        msg='Appoinment Not done'
        
    return render(request,'myhospital_app/booking.html',{'doctor':doctor,'departments':departments,'slots':slots})
def home(request):
    doctor=Doctor.objects.all()
    return render(request,'myhospital_app/home.html',{'doctor':doctor})

def demo(request):
    return render(request,'myhospital_app/demo.html')

def patient_portal(request):
    msg = ''
    if request.method == 'POST':
        patient_id = request.POST['patient_id']
        password = request.POST['password']
        
        try:
            patient = Patient.objects.get(email=patient_id,password=password)
            request.session['patient']=patient.id
            return redirect('patient:home')
        except:
            msg= 'Incorrect Username Or Password'
    else:
        msg='error'        
    return render(request,'myhospital_app/patient_portal.html')

def staff_login(request):
    msg = ''
    if request.method == 'POST':
        staff_id = request.POST['staff_id']
        password = request.POST['password']
        
        try:
            staff = Staff.objects.get(staffid=staff_id,password=password)
            request.session['staff']=staff.id
            return redirect('staff:master')
        except:
            msg= 'Incorrect Username Or Password'
    
    return render(request,'myhospital_app/staff_login.html')

def doctor_login(request):
    msg = ''
    if request.method == 'POST':
        doctor_id = request.POST['doctor_id']
        password = request.POST['password']
        
        try:
            doctor = Doctor.objects.get(doctorid= doctor_id,password=password)
            request.session['doctor']=doctor.id
            return redirect('doctor:home')
        except:
            msg= 'Incorrect Username Or Password'
    return render(request,'myhospital_app/doctor_login.html')

def admin(request):
    msg=''
    if request.method=='POST':
        user_name =request.POST['username']
        password = request.POST['password']

        try:
            admin = Admin.objects.get(user_name = user_name , password = password)
            request.session['admin']= admin.id
            return redirect('admin_app:home')
        
            
        except:
            msg='Incorrect Username or password'

    
    return render(request,'myhospital_app/admin_login.html',{'message':msg})

def about_us(request):
    return render(request,'myhospital_app/about_us.html')

def contact(request):
    return render(request,'myhospital_app/contact.html')


def get_doctors(request):
    department_id = request.GET.get('department_id')
    doctors = Doctor.objects.filter(department_id=department_id)
    doctor_list = [{'id': doctor.id, 'name': doctor.name} for doctor in doctors]
    return JsonResponse(doctor_list, safe=False)


 

def get_day(request):
    doctor_id=request.GET['doctor_id']
    days = Slots.objects.filter(doctor_id = doctor_id)
     
    
    day_list = [{'id':slot.id,'day':slot.day}for slot in days]
    return JsonResponse(day_list, safe=False)
    
def get_time(request):
    slots_id = request.GET['slots_id']
    time = Slots.objects.filter(id=slots_id).values('time')
    time_list = [{'time': slot['time']} for slot in time]
    return JsonResponse(time_list, safe=False)


def patient_register(request):
    mail = ''
    msg = ''
    if request.method == 'POST':
        patient_name = request.POST['name']
        patient_age = request.POST['age']
        patient_dob = request.POST['dob']
        patient_gender = request.POST['gender']
        patient_mobile = request.POST['phone']
        patient_mail = request.POST['email']
        patient_place = request.POST['place']
        mobile_exists = Patient.objects.filter(phone = patient_mobile).exists()
        
        if not mobile_exists:
            new_patient= Patient(
                name=patient_name,
                age=patient_age,
                dob=patient_dob,
                gender=patient_gender,
                phone=patient_mobile,
                email=patient_mail,
                place=patient_place
            )
            new_patient.save()
            
            mail='uour id '+str(patient_mail)+'and password is '+'12345678'
            msg ='Registered Successfully'
            send_mail(
                'You have been successfully registerd' ,
                mail,
                settings.EMAIL_HOST_USER,
                [new_patient.email]
            )
    else:
        msg='Error'
        
        
        
    return render(request,'myhospital_app/patient_register.html')

myhospital_app/templates/myhospital_app/Staff_login.html
{% extends "myhospital_app/master.html" %}
{% load static %}
{% block header %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<script src="{% static 'js/login_validations.js' %}"></script>

{% endblock %}



{% block content %}

<h1>STAFF LOGIN</h1>

 
<div class="container-fluid login_parent">
	<div class="log_form">
		<img src="{% static 'image/staff_login.png' %}" alt="" class="logimg" height="370px">

	</div>
	 
	<div class="log_form">
		<h1>Login</h1>
		<form method='POST'>
			{% csrf_token %}
		  <label for="username">Hospital ID:</label>
		  <input type="text" id="id" name="staff_id" required><span id="id_span"></span>
		  <label for="password">Password:</label>
		  <input type="password" id="password" name="password" required><span id="password_span"></span>
		  <input type="submit" value="Login" onclick=""> <p class="signup-link">
			Not a staff !
			<a href="login">Patient login</a> 
		  </p>
		</form>
	  </div>
	  

	  
</div>	
 {% endblock %}

myhospital_app/templates/myhospital_app/about_us.html
{% extends "myhospital_app/master.html" %}
{% load static %}
{% block header %}

<style>
    body {
        font-style: normal;
        line-height: 1.6;
        margin: 0;
        padding: 0;
        background-color: white;
    }



    .container {
        max-width: 800px;
        margin: 0 auto;
        padding: 20px;
    }

    h1 {
        color: darkcyan;
        padding-top: 50px;


        
        font-family: fantasy;
    }

    h2 {
        color: darkcyan;
    }

     

    p {
         
         font-family: 'Times New Roman', Times, serif;
         font-weight: 400;
    }

    .mission-values {
        display: flex;
        justify-content: space-between;
        margin-bottom: 30px;
    }

    .mission-values div {
        flex: 1;
        padding: 10px;


        border-radius: 5px;
    }

    .services {
        list-style: none;
        padding: 0;
    }

    .services li {
        margin-bottom: 10px;
    }

    .heading {
        display: flex;
        flex-direction: column;
        font-size: x-large;
        height: 800px;
        background-image: url(https://wallpaperaccess.com/full/3464162.jpg);
    }
</style>

{% endblock %}




{% block content %}

<div class="container-fluid heading">
    <h1>About Us</h1>
     
     
    <p>Welcome to My hospital where we prioritize the health and well-being of our patients. Our hospital is
        dedicated to providing top-notch medical care, advanced technology, and compassionate services to the community.
    </p>
    <p>In Our new website, We encourage you to find out more about the values and vision that guides us, the
        services and programs we offer, the indicators that ensure our continued accountability and transparency, and
        the news and events that matter most to you. It is the place where you will find information on career
        opportunities with HMH and be able to access general healthcare information to keep you well informed.</p>
</div>



<div class="container">


    <div class="mission-values">
        <div>
            <h2>Our Mission</h2>
            <p>We aim to improve the quality of life for our patients by delivering exceptional healthcare with
                integrity and empathy.</p>
        </div>
        <div>
            <h2>Our Values</h2>
            <p>We uphold the following values in all our interactions and services:</p>
            <ul>
                <li>Compassion</li>
                <li>Excellence</li>
                <li>Respect</li>
                <li>Innovation</li>
                <li>Collaboration</li>
            </ul>
        </div>
    </div>

    <h2>Our Services</h2>
    <ul class="services">
        <li>General Medicine</li>
        <li>Emergency and Trauma Care</li>
        <li>Surgery and Specialized Procedures</li>
        <li>Maternity and Obstetrics</li>
        <li>Pediatrics</li>
        <li>Diagnostic Imaging</li>
        <li>Rehabilitation Services</li>
        <li>Mental Health Services</li>
        <li>And more...</li>
    </ul>
</div>

{% endblock %}

myhospital_app/templates/myhospital_app/admin_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body{
            text-align: center;
            font-size: larger;
            font-family: 'Times New Roman', Times, serif;
            background-color: #4682A9;
        }
        h1{
            margin-top: 2%;
            
        
        }
        .main{
            display: flex;
            justify-content: center;
        }
        
        
        
        
        .login_parent{
            display: flex;
            justify-content: space-evenly;
            border-radius: 5px;
            flex-wrap: wrap;
            margin: 50px;
            position: relative;
            right: 50px;
             
            
             
        
        }
        /* .login_parent:hover {
            box-shadow: 0px 0px 10px rgba(1, 1, 1, 0.2);
        
        } */
        
        
        .log_form {
            max-width: 500px;
            height: 300px;
            margin: 0;
            padding: 50px;
            background-color: white;
            border-radius: 10px;
            text-align: center;
           }
         
          
          h1 {
            font-size: 36px;
            margin-bottom: 30px;
            color: black;
          }
          
          form {
            display: inline-block;
            text-align: left;
          }
          
          label {
            display: block;
            margin-bottom: 10px;
          }
          
          input[type="text"], input[type="password"] {
            padding: 10px;
            width: 100%;
            border-radius: 5px;
            border: 1px solid #ccc;
            margin-bottom: 20px;
            box-sizing: border-box;
          }
          
          input[type="submit"] {
            padding: 10px 20px;
            background-color: #4CAF50;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
          }
          .logimg{
            width: 155%;
        
          }

    </style>
</head>
<body>
    <h1>ADMIN LOGIN</h1>

 
<div class="container-fluid main">
	 
	<div class="log_form">
		<h1>Login</h1>
		<form method="POST">
            {% csrf_token %}
		  <label for="username">Username :</label>
		  <input type="text" id="username" name="username" required placeholder=""><span id="username_span"></span>
		  <label for="password">Password:</label>
		  <input type="password" id="password" name="password" required>
		  <span id="password_span"></span>
		 <input type="submit" value="Login">  
     {{ message }}
 		</form>
        <div><a href="{% url 'myhospital_app:home' %}">Home</a></div>
	  </div>

	  

	  
</div>	
</body>
</html>

myhospital_app/templates/myhospital_app/doctor_login.html
{% extends "myhospital_app/master.html" %}
{% load static %}
{% block header %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<script src="{% static 'js/login_validations.js' %}"></script>

{% endblock %}



{% block content %}

<h1>DOCTOR LOGIN</h1>

 
<div class="container-fluid login_parent">
	<div class="log_form">
		<img src="{% static 'image/doctor_login.jpg' %}" alt="" class="logimg" height="350px">

	</div>
	 
	<div class="log_form">
		<h1>Login</h1>
		<form method="POST">
            {% csrf_token %}
			
		  <label for="username">Doctor ID:</label>
		  <input type="text" id="id" name="doctor_id" required><span id="id_span"></span>
		  <label for="password">Password:</label>
		  <input type="password" id="password" name="password" required><span id="password_span"></span>
		  <input type="submit" value="Login" onclick="">
		</form>
	  </div>
	  <p>3654</p>

	  
</div>	
 {% endblock %}

myhospital_app/templates/myhospital_app/home.html
{% extends "myhospital_app/master.html" %}
{% load static %}
{% block header %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
<link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />

{% endblock %}



{% block content %}
<section>
    <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'image/poster4.jpg' %}" class="d-block w-100" alt="..">
            </div>
            <div class="carousel-item">
                <img src="{% static 'image/poster3.jpg' %}" class="d-block w-100" alt="...">
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying"
            data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying"
            data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</section>


<div id="login_section">

    <div class="child_login" data-aos="fade-right" data-aos-duration="7000" data-aos-easing="ease-in-out">

        <h2>New to the Hospital?</h3>
            <p>Make an appoinment through our website its simple and easy .orem ipsum, dolor sit amet consectetur
                adipisicing elit. Modi accusantium illum illo iure omnis dolor
                L animi maxime quam nostrum voluptates Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                Eveniet, repudiandae</p>
            <a href="{% url 'myhospital_app:patient_register' %}"> <button type="button" class="btn btn-outline-success">Go</button></a>
    </div>

    <div class="child_login" data-aos="fade-left" data-aos-duration="7000" data-aos-easing="ease-in-out">
        <a href="{% url 'myhospital_app:patient_register' %}"> <img src="{% static 'image/patient_portal.png' %}" alt=""></a>

    </div>

</div>



<section>
    <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'image/poster2.jpg' %}" class="d-block w-100" alt="..">
            </div>
            <div class="carousel-item">
                <img src="{% static 'image/poster.jpg' %}" class="d-block w-100" alt="...">
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying"
            data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying"
            data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</section>



<section class="dep-section">



    <div class="dep-heading" data-aos="fade-up" data-aos-duration="7000" data-aos-easing="ease-in-out">
        <h1>OUR DEPARTMENTS</h1>
    </div>
    <div class="department container-fluid" data-aos="fade-up" data-aos-duration="7000" data-aos-easing="ease-in-out">


        <div class="child-dep">
            <div class=""><img src="{% static 'image/dep1.jpg' %}" alt=""></div>
            <div class="">
                <h3>General Medicine</h3>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nulla, praesentium. Lorem ipsum dolor sit
                    amet
                    consectetur adipisicing elit. Quo nulla molestiae nam sequi omnis odit sed repellat facilis rerum
                    ipsam.
                </p>
            </div>
        </div>
        <div class="child-dep">
            <img src="{% static 'image/dep2.jpg' %}" alt="">
            <h3>Cardiology</h3>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptates nemo officiis dolorum! Animi modi,
                vero
                mollitia eos necessitatibus consequatur, adipisci nesciunt, fugit quam unde deleniti.</p>


        </div>
        <div class="child-dep">
            <img src="{% static 'image/dep3.jpg' %}" alt="" width="400px">
            <h3>Neurology</h3>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Recusandae quos quisquam voluptate sapiente
                voluptates reprehenderit, ipsa ipsum totam, nostrum ab omnis molestiae placeat, suscipit assumenda!</p>

        </div>
        <div class="child-dep">
            <img src="{% static 'image/dep4.jpg' %}" alt="">
            <h3>Gynecology</h3>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Similique modi eligendi laudantium pariatur
                saepe,
                molestias mollitia, aliquam natus, dolor consequatur officiis magnam praesentium cum nemo.</p>

        </div>




    </div>
    <div class="dep-button" data-aos="fade-up" data-aos-duration="7000" data-aos-easing="ease-in-out">
        <button type="button" class="btn btn-outline-success">Show More</button>
    </div>
</section>

<br>

<div class="container-fluid false-section">
    <div class="container-fluid" style="padding-top: 50px;"><img src="           " alt=""
            width="100%"></div>
</div>



<div class="container mt-5 mb-5">
    <div class="row">
{% for i in doctor %}
     <div class="cards col-md-3">
        <div class="card-image">
            <img src="{{i.image.url}}" alt=".." width="50%">
        </div>
        <div class="card-texts">
            <h4>{{i.name |title}}</h4>
            <h6>{{i.department.name |title}}</h6>

        </div>
     </div>
     {% endfor %}
     </div>
</div>






<script src="https://unpkg.com/aos@next/dist/aos.js"></script>
<script>
    AOS.init({
        once: true,
    });
</script>

{% endblock %}

myhospital_app/templates/myhospital_app/master.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
<link rel="stylesheet" href="{% static 'css/master.css' %}">
<link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/font-awesome-line-awesome/css/all.min.css">
<link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">
    {% block header %}

    {% endblock %}
</head>

<body>
    

     
        <header>
            <nav class="navbar navbar-expand-lg bg-body-tertiary">
                <div class="container-fluid">
                  <a class="navbar-brand" href="#"><img src="{% static 'image/logo.png' %}" alt="" width="60px"></a>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="home">Home</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link " href="{% url 'myhospital_app:patient_portal' %}">Patient Portal</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'myhospital_app:about_us' %}">About us</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'myhospital_app:contact' %}">Contact us</a>
                      </li>
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Login
                        </a>
                        <ul class="dropdown-menu">
                          <li><a class="dropdown-item" href="login">Login as Patient</a></li>
                          <li><a class="dropdown-item" href="doctor_login">Login as Doctor</a></li>
                          <li><a class="dropdown-item" href="staff_login">Login as Staff</a></li>
                          <li><a class="dropdown-item" href="{% url 'myhospital_app:admin_login' %}">Login as Admin</a></li>

                        </ul>
                      </li>
                       
                      
                       
                    </ul>
                    <div>
                     <a href="{% url 'myhospital_app:booking' %}"> <button class="btn btn-outline-success" type="button">Make Appoinment</button></a>
                    </div>
                  </div>
                </div>
              </nav>
        </header>
         
        
     
<div class="content"> 
{% block content %}

{% endblock %}
</div>
<hr>
<footer>
  <div class="footer">
    <div class="footer_child">
 
      <h3>Hospital Links</h3>
      <h6>
        <a href="{% url 'myhospital_app:home' %}">> Home</a> <br>
        <a href="{% url 'myhospital_app:about_us' %}">> About Us</a> <br>
         > Privacy Policy <br>
         > Terms and conditions  <br>
         > Charity Program  <br>
        <a href="{% url 'myhospital_app:contact' %}">> Contact Us</a> <br>
        

      </h6>

    </div>
    <div class="footer_child">
      <h3>Information Links</h3>
      <h6>
        <a href="{% url 'myhospital_app:home' %}">> Departments</a> <br>
        <a href="{% url 'myhospital_app:home' %}">> Our Doctors</a> <br>
        <a href="{% url 'myhospital_app:home' %}">> Services</a> <br>
         

      </h6>

    </div>
    <div class="footer_child">
       
      <h3>Other Links</h3>
      <h6>
        <a href="{% url 'myhospital_app:home' %}">> Online Appoinment</a> <br>
        <a href="{% url 'myhospital_app:home' %}">> Online Lab Report</a> <br>
        <a href="{% url 'myhospital_app:home' %}">> Feedback</a> <br>
        

      </h6>

    </div>
    <div class="footer-child">
      <h3>Contact Us</h3>
      <h6>
        My hospital International Hospital <br>
        Calicut Kerala India <br>
        0496 496 265420
        myhospital@gmail.com
      </h6>

    </div>
    

     

  </div>
  
</footer>

</body>

</html>

myhospital_app/templates/myhospital_app/patient_portal.html
{% extends "myhospital_app/master.html" %}
{% load static %}
{% block header %}
<link rel="stylesheet" href="{% static 'css/patient_portal.css' %}">

{% endblock %}



{% block content %}


<section class="main-section">

  <div class="patient-portal">

<div class=""><h3>New to the Hospital?</h3>
  <p><h6><a href="{% url 'myhospital_app:patient_register' %}">Register</a> as a patient and track your activity.</h6>orem ipsum, dolor sit amet consectetur
    adipisicing elit. Modi accusantium illum illo iure omnis dolor
    L animi maxime quam nostrum voluptates Lorem ipsum dolor, sit amet consectetur adipisicing elit.
    Eveniet, repudiandae</p>
</div>
<div class="portal-background">
<img src="https://www.emedstore.in//blogadmin/uploads/post/main/Telemedicine-Main(Blog)_POST_1617701385.png" alt="" width="900px">
</div>


  </div>
  

  <div class="login-section">

    <div class="login_form">
      <h1>Login</h1>
      <form method="POST">
        {% csrf_token %}

        <label for="username">Email:</label>
        <input type="text" id="id" name="patient_id"><span id="id_span"></span>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required>
        <span id="password_span"></span>
        <input type="submit" value="Login" onclick="">
      </form>
      <a href="home"></a>
      <p class="signup-link">
        No account?
        <a href="register">Sign up</a>
      </p>
    </div>

  </div>



</section>











{% endblock %}