admin_app/urls.py
from django.urls import path
from .import views

app_name= 'admin_app'

urlpatterns =[
    path('admin_master',views.admin_master,name='admin_master'),
    path('admin_doctor',views.admin_doctor,name='admin_doctor'),
    path('add_doctor',views.add_doctor,name='add_doctor'),
    path('home',views.home,name='home'),
    path('staffs',views.staffs,name='staffs'),
    path('staff/register',views.staff_reg,name='staff_register'),
    path('logout',views.logout,name='logout'),
    path('doctor/records',views.doc_records,name='doc_records'),
    path('staff/records',views.staff_rec,name='staff_rec'),
    path('departments',views.departments,name='departments'),
    path('appoinments',views.appoinments,name='appoinments'),
    path('slot/managment/<int:d_id>',views.slot_managment,name='slot_managment'),
    path('slot',views.slot,name='slot'),
    path('doctor_profile/<int:d_id>',views.doctor_profile,name='doctor_profile'),
    path('remove_doctor/<int:Did>',views.remove_doctor,name='remove_doctor'),
    path('view/slots/<int:d_id>',views.view_slots,name='view_slots'),
    path('delete/slots/<int:s_id>',views.delete_slot,name='delete_slot'),
    
    
    
    
    
    
     
    
    
    
    
    
    
]

myhospital/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myhospital_app.urls')),
    path('admin_app/',include('admin_app.urls')),
    path('doctor/',include('doctor.urls')),
    path('staff/',include('staff.urls')),
    path('patient/',include('patient.urls')),
    
    
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

staff/urls.py
from django.urls import path
from .import views

app_name='staff'

urlpatterns =[
    path('master',views.master,name='master'),
    path('home',views.home,name='home'),
    path('patients',views.patients,name='patients'),
    path('appoinments',views.appoinments,name='appoinments'),
    path('logout',views.logout,name='logout'),
    
    
    
    
    
]

admin_app/models.py
from django.db import models

 


# Create your models here.

class Admin(models.Model):
    user_name = models.CharField(max_length=30)
    password = models.CharField(max_length=30)

    class Meta:
        db_table = 'admin_tb'
        
        
class Departments(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to = 'departments', default='')
    
    class Meta:
        db_table = 'departments_tb'
        


    

staff/models.py
from django.db import models

# Create your models here.

class Staff(models.Model):
    name = models.CharField(max_length=30)
    age= models.CharField(max_length=30)
    department = models.CharField(max_length=50)
    qualification = models.CharField(max_length=100)
    staffid = models.CharField(max_length=30)
    password = models.CharField(max_length=30,default='')
    email = models.CharField(max_length=30)
    mobile = models.BigIntegerField()
    image = models.ImageField(upload_to = 'staff')
    

    class Meta:
        db_table = 'staff_tb'

admin_app/views.py
from django.shortcuts import render,redirect
from doctor.models import Doctor
from staff.models import Staff
from .models import Admin,Departments
import random
from django.core.mail import send_mail
from django.conf import settings
from django.db.models import F
from .decorator import auth_admin
from myhospital_app .models import Patient
from patient.models import Slots


# Create your views here.
@auth_admin
def admin_master(request):
    return render(request,'admin_app/admin_master.html')
@auth_admin
def home(request):
    return render(request,'admin_app/home.html')
@auth_admin
def admin_doctor(request):
    return render(request,'admin_app/admin_doctor.html')

@auth_admin
def add_doctor(request):
    departments = Departments.objects.all()
    mail = ''
    msg=''
    if request.method =='POST':
        doctor_name = request.POST['name']
        doctor_age = request.POST['age']
        department = request.POST['department']
        qualification = request.POST['qualification']
        doctor_id = random.randint(1111,4444)
         
        email = request.POST['email']
        mobile_no = request.POST['mobile']
        image = request.FILES['image']
        
        new_doctor = Doctor(
            name = doctor_name,                                         
            age = doctor_age,
            department_id = department,
            qualification = qualification,
            doctorid = doctor_id,
             
            email = email,
            mobile = mobile_no,
            image = image
        )
        new_doctor.save()
        
        # sending mail to registred user
        
        mail='uour id '+str(doctor_id)+'and password is '+'12345678'
        msg ='Registered Successfully'
        send_mail(
            'You have been successfully registerd' ,
            mail,
            settings.EMAIL_HOST_USER,
            [new_doctor.email]
        )
    else:
        msg='Error'
    
    return render(request,'admin_app/add_doctor.html',{'departments':departments})

def staffs(request):
    return render(request,'admin_app/staffs.html')

def staff_reg(request):
    department = Departments.objects.all()
    mail =''
    msg=''
    if request.method =='POST':
        staff_name = request.POST['name']
        staff_age = request.POST['age']
        department = request.POST['department']
        qualification = request.POST['qualification']
        staff_id = random.randint(5555,9999)
        password = request.POST['password']
        email = request.POST['email']
        mobile_no = request.POST['mobile']
        image = request.FILES['image']
        mail_exists = Staff.objects.filter(email = email).exists()
        
        if not mail_exists:
            
            new_staff = Staff(
                name = staff_name,
                age = staff_age,
                department = department,
                qualification = qualification,
                staffid = staff_id,
                password = password,
                email = email,
                mobile = mobile_no,
                image = image
            )
            new_staff.save()
            mail = 'You have Succesfully Appointed your id '+str(staff_id)+'password '+str(password)
            msg ='Registered Successfully'
            send_mail(
                 'Welcome To MY HOSPITAL' ,
            mail,
            settings.EMAIL_HOST_USER,
            [new_staff.email]
            )
        
        else:
            msg='Mail already exists in Database'
    
    return render(request,'admin_app/staff_register.html',{'msg':msg,'department':department})

def logout(request):
    del request.session['admin']
    request.session.flush()
    return redirect( 'myhospital_app:home' )

def doc_records(request):
    doctor = Doctor.objects.all()
    return render(request,'admin_app/doctor_records.html',{'doctors':doctor})

def staff_rec(request):
    staff = Staff.objects.all()
    return render(request,'admin_app/staff_records.html',{'staff':staff})

def departments(request):
    dep = Departments.objects.all()
    msg=''
    if request.method =='POST':
        dep_name = request.POST['department_name']
        
        image = request.FILES['image']
        dep_exists = Departments.objects.filter(name=dep_name).exists()
        if not dep_exists:
            new_department = Departments(
                name = dep_name,
                image = image
            
                
            )
            new_department.save()
            msg = 'Added Succesfully'
        else:
            msg='Department Already Exists'
    return render(request,'admin_app/department.html',{'msg':msg,'dep':dep})

def appoinments(request):
    appoinment = Patient.objects.filter(status='pending') 
    return render(request,'admin_app/appoinments.html',{'appoinments':appoinment})

def slot(request):
    doctor = Doctor.objects.all()
    return render(request,'admin_app/slot.html',{'doctors':doctor})

def view_slots(reuqest,d_id):
    doctors = Doctor.objects.get(id=d_id)
    slot = Slots.objects.filter(doctor=doctors)
    
    
    return render(reuqest, 'admin_app/view_slots.html',{'doctor':doctors,'slot':slot})

#adding slots to doctor
def slot_managment(request, d_id):
    msg = ''
    doctor = Doctor.objects.get(id=d_id)
    
    if request.method == 'POST':
        day = request.POST['day']
        from_time = request.POST['from_time']
        to_time = request.POST['to_time']
        time_range = f"{from_time}-{to_time}"  #f-strings(formatted strings) to concatenate the 'from_time' and 'to_time' values with a hyphen '-' in between them.
        
        existing_slot = Slots.objects.filter(doctor=doctor, day=day, time=time_range).first()

        if existing_slot:
            msg = 'Slot already exists.'
        else:
            new_slot = Slots(doctor=doctor, day=day, time=time_range)
            new_slot.save()
            msg = 'Slot added successfully'
        
             
         
        
    return render(request, 'admin_app/slot_managment.html', {'doctor': doctor, 'msg': msg})

def delete_slot(reuqest,s_id):
    try:
    
        slot = Slots.objects.get(id = s_id) 
        slot.delete()   
        
        return redirect('admin_app:view_slots')
    
    except Slots.DoesNotExist:
        
        pass


def doctor_profile(request, d_id):
    doctors = Doctor.objects.get(id=d_id)
    return render(request,'admin_app/doctor_profile.html',{'doctor':doctors})

# def doctor_satus_update(request,Did):
     
#     doctor = Doctor.objects.get(id=Did)
#     doctor.status='on leave'
#     doctor.save()
#     msg ='Dr'+str(doctor.name)+' You are kindly removed of your Duty in MyHospital.We Thankyou for your service'
#     send_mail(
#             subject = 'Your account was Approved',
#             message = msg,
#             from_email = 'msfidal2001@gmail.com',
#             recipient_list = [doctor.email]
            
#         )
#     return redirect('admin:doc_records')

def remove_doctor(request, Did):
    try:
        doctor = Doctor.objects.get(id=Did)
        doctor_name = doctor.name
        doctor_email = doctor.email
        doctor.delete()
        
        msg = f'Dr {doctor_name}, you have been removed from MyHospital. Thank you for your service.'

        send_mail(
            subject='Doctor Removal Notification',
            message=msg,
            from_email='msfidal2001@gmail.com',
            recipient_list=[doctor_email]
        )

        return redirect('admin_app:doc_records')
    except Doctor.DoesNotExist:
        # Handle the case where the doctor with the provided ID does not exist.
        # You can customize this error handling according to your needs.
        pass

staff/views.py
from django.shortcuts import render,redirect

# Create your views here.

def master(request):
    return render(request,'staff/master.html')

def home(request):
    return render(request,'staff/home.html')

def patients(request):
    return render(request,'staff/patients.html')

def appoinments(request):
    return render(request,'staff/appoinments.html')

def logout(request):
    del request.session['staff']
    request.session.flush()
    return redirect( 'myhospital_app:home' )

admin_app/templates/admin_app/add_doctor.html
{% extends "admin_app/admin_master.html" %}
{% load static %}
{% block header %}
<style>
	form {
		display: flex;
		flex-direction: column;
		align-items: center;

		margin-top: 50px;
	}

	.form {
		display: flex;
		flex-direction: column;
		align-items: center;
	}

	input[type=text],input[type=password],input[type=file],select {
		margin: 10px;
		padding: 10px;
		width: 500px;
		border-radius: 5px;
		border: 1px solid #ccc;
	}

	input[type=submit] {
		background-color: #4CAF50;
		color: white;
		border: none;
		padding: 10px 20px;
		text-align: center;
		text-decoration: none;
		display: inline-block;
		font-size: 16px;
		margin: 10px;
		border-radius: 5px;
		cursor: pointer;
	}

	label {
		margin: 10px;
	}

	.signup {
		text-align: center;
	}
</style>

{% endblock %}



{% block content %}

<div style="text-align: start;"><button onclick="history.back()" class="back-button"><- Go Back</button></div>


<div class="container-fluid form">
	<div class="" style="text-align: center; margin-top: 20px; margin-bottom: 20px;">
		<h3>ADD DOCTOR</h3>
	</div>
	<table>
		{{ msg }}



		<form action="" method="POST" enctype="multipart/form-data">
			{% csrf_token %}

			<tr>
				<td><label for="name">Name :</label></td>
				<td><input type="text" id=" " name="name"></td>
			</tr>

			<tr>
				<td><label for="age">Age :</label></td>
				<td><input type="text" name="age"></td>
			</tr>

            <tr>
				<td><label for="">Department :</label></td>
				<td><select name="department" id="department">
					<option value="" selected disabled>Select Department</option>
					{% for i in departments %}
					<option value="{{i.id}}">{{i.name |title}}</option>
					{% endfor %}
					 
				</select></td>
			</tr>
			<tr>
				<td><label for="">Qualification :</label></td>
				<td><input type="text" name="qualification"></td>
			</tr>

             
            

			<tr>
				<td><label for="email">Email :</label></td>
				<td><input type="text" name="email"></td>

			</tr>
            <tr>
				<td><label for="mobile">Mobile :</label></td>
				<td><input type="text" name="mobile"></td>

			</tr>

			<tr>
				<td><label for="image">Image</label></td>
				<td><input type="file" name="image"></td>
			</tr>
			<tr>
				<td></td>
				<td><input type="submit" value="Submit"></td>
			</tr>

		</form>
	</table>
</div>

{% endblock %}

admin_app/templates/admin_app/admin_doctor.html
{% extends "admin_app/admin_master.html" %}
{% load static %}
{% block header %}
<style>



</style>

{% endblock %}



{% block content %}
<div class="container-fluid admin-cards ">

  <a href="{% url 'admin_app:add_doctor' %}">
    <div class="card cards mb-3" style="max-width: 340px; max-height:120px;">
      <div class="row g-0">
        <div class="col-md-4">
          <img src="https://cdn-icons-png.flaticon.com/512/3456/3456388.png" class="img-fluid rounded-start" alt="..."
            width="350px">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h2 class="card-title">Register Doctor</h2>
            <h3></h3>
            <h6></h6>
          </div>
        </div>
      </div>
    </div>
  </a>

  <a href="{% url 'admin_app:doc_records' %}">

    <div class="card cards mb-3" style="max-width: 340px; max-height:200px; ">
      <div class="row g-0">
        <div class="col-md-4">
          <img src="{% static 'image/doctor.png' %}" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h2 class="card-title">Doctors Records</h2>
            <h3></h3>
  
          </div>
        </div>
      </div>
    </div>

  </a>



  <div class="card cards mb-3" style="max-width: 340px; max-height:200px;">
    <div class="row g-0">
      <div class="col-md-4">
        <img
          src="https://cdn-icons-png.flaticon.com/512/166/166256.png"
          class="img-fluid rounded-start" alt="...">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h2 class="card-title">Update Profile</h2>
          <h3></h3>

        </div>
      </div>
    </div>
  </div>


</div>




{% endblock %}

admin_app/templates/admin_app/admin_master.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
  <link rel="stylesheet" href="{% static 'css/masterpage-admin.css' %}">
  <link rel="stylesheet"
    href="https://maxst.icons8.com/vue-static/landings/line-awesome/font-awesome-line-awesome/css/all.min.css">
  <link rel="stylesheet"
    href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">

  {% block header %}

  {% endblock %}
</head>


<body>
  <div class="container-fluid maindiv">

    <!-- header  -->

    <div class="row container-fluid">
      <div class="col-sm-2 dashboard1">
        <div class=" "><img src="{% static 'image/admin-logo.png' %}" alt="" width="60px" class="admin-logo"></div>

      </div>


      <div class="col-sm-10 navbarr">

        <a href="">
          <div class="nav-items"></div>
        </a>


        <div class="nav-items " data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@mdo"><img
            src="{% static 'image/logo.png' %}" alt="" width="60px" class=""></div>

      </div>
    </div>


    <div class="row container-fluid">
      <div class=" col-sm-2 dashboard2">

        <a href="{% url 'admin_app:home' %}">
          <div class="dash1 "><i class="las la-igloo">Dashboard</i></div>
        </a>

        <a href="{% url 'admin_app:departments' %}">
          <div class="dash-elements"> <i class="las la-igloo">Departments</i></div>
        </a>

        <a href="{% url 'admin_app:admin_doctor' %}">
          <div class="dash-elements"><i class="las la-stethoscope">Doctors</i></div>
        </a>

        <a href="{% url 'admin_app:slot' %}">
          <div class="dash-elements"><i class="las la-cube">Slot</i></div>
        </a>

        <a href="{% url 'admin_app:appoinments' %}">
          <div class="dash-elements"> <i class="las la-calendar-check">Appoinments</i></div>
        </a>
        <a href="">
          <div class="dash-elements"><i class="las la-user-injured">Patients</i></div>
        </a>
        
         
        
        
        <div class="logout"><a href="{% url 'admin_app:logout' %}"><button type="button" class="btn btn-danger"> logout</button></a></div>



      </div>











      <div class="col-sm-10 content">
        {% block content %}


        {% endblock %}

      </div>
    </div>
  </div>


</body>

</html>

admin_app/templates/admin_app/appoinments.html
{% extends "admin_app/admin_master.html" %}
{% load static %}
{% block header %}
<style>
    table {
        width: 100%;
        border-collapse: collapse;
        
      }
      
      th, td {
         
        padding: 8px;
        text-align: left;
        border-bottom: 1px solid #ddd;
      }
      
      th {
        background-color: #f2f2f2;
      }
      
      tr:hover {
        background-color: #f5f5f5;
      }
      .doc-rec{
        padding-top: 50px;
      }

</style>

{% endblock %}



{% block content %}

 
<div class="container-fluid doc-rec">
    

    <table>
        <tr>
          <th>Name</th>
          <th>Age</th>
          <th>Email</th>
          <th>Mobile</th>
          <th>Assigned Doctor</th>
          <th>Department</th>
          <th>Appoinment Date</th>

          <th>Status</th>

          
        </tr>
        {% for i in appoinments %} 
        <tr>
          <td>{{i.name}}</td>
          <td></td>
          <td></td>
          <td>{{i.doctor}}</td>
          <td></td>
          <td></td>
          <td>{{i.Status}}</td>
       
           
    
        </tr>
        {% endfor %}
         
      </table>
    </div>
    
 

{% endblock %}

admin_app/templates/admin_app/doctor_profile.html
{% extends "admin_app/admin_master.html" %}
{% load static %}
{% block header %}
<style>



</style>

{% endblock %}




{% block content %}

{{doctor.name}}

{% endblock %}

admin_app/templates/admin_app/doctor_records.html
{% extends "admin_app/admin_master.html" %}
{% load static %}
{% block header %}
<style>
  table {
    width: 100%;
    border-collapse: collapse;

  }

  th,
  td {

    padding: 8px;
    text-align: center;
    border-bottom: 1px solid #ddd;
  }

  th {
    background-color: #f2f2f2;
  }

  tr:hover {
    background-color: #f5f5f5;
  }

  .doc-rec {
    padding-top: 50px;
  }
  
</style>

{% endblock %}



{% block content %}


<div style="text-align: start;"><button onclick="history.back()" class="back-button"><- Go Back</button></div>


<div class="container-fluid doc-rec">
  <table>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Age</th>
      <th>Email</th>
      <th>Mobile</th>
      <th>Department</th>
      <th>Image</th>
      <th>Profile</th>
      <th>Remove </th>
    </tr>
    {% for doctor in doctors %}
    
      <tr>
        <td>{{doctor.doctorid}}</td>
        <td>{{doctor.name}}</td>
        <td>{{doctor.age}}</td>
        <td>{{doctor.email}}</td>
        <td>{{doctor.mobile}}</td>
        <td>{{doctor.department.name}}</td>
        <td><img src="{{doctor.image.url}}" alt="" width="100px"></td>
        <td><a href="{% url 'admin_app:doctor_profile' doctor.id %}">view</a></td>
        <td><a href="{% url 'admin_app:remove_doctor' doctor.id %}">remove</a></td>

      </tr>
    {% endfor %}
  </table>
</div>

{% endblock %}

admin_app/templates/admin_app/slot.html
{% extends "admin_app/admin_master.html" %}
{% load static %}
{% block header %}
<style>
	table {
        width: 100%;
        border-collapse: collapse;
    
      }
    
      th,
      td {
    
        padding: 8px;
        text-align: center;
        border-bottom: 1px solid #ddd;
      }
    
      th {
        background-color: #f2f2f2;
      }
    
      tr:hover {
        background-color: #f5f5f5;
      }
    
      .doc-rec {
        padding-top: 50px;
      }

</style>

{% endblock %}



{% block content %}
<div class="container-fluid doc-rec">
    <table>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Age</th>
          <th>Email</th>
          <th>Mobile</th>
          <th>Department</th>
          <th>Image</th>
          <th>View Slots</th>
          <th>Add Slots</th>
        </tr>
        {% for doctor in doctors %}
        <tr>
          <td>{{doctor.doctorid}}</td>
          <td>{{doctor.name}}</td>
          <td>{{doctor.age}}</td>
          <td>{{doctor.email}}</td>
          <td>{{doctor.mobile}}</td>
          <td>{{doctor.department.name}}</td>
          <td><img src="{{doctor.image.url}}" alt="" width="100px"></td>
          <td><a href="{% url 'admin_app:view_slots' doctor.id %}">VIew</a></td>
          <td><a href="{% url 'admin_app:slot_managment' doctor.id %}">Add</a></td>
    
        </tr>
         {% endfor %}
      </table>
    </div>
{% endblock %}

admin_app/templates/admin_app/slot_managment.html
{% extends "admin_app/admin_master.html" %}
{% load static %}
{% block header %}
<style>
	form {
		display: flex;
		flex-direction: column;
		align-items: center;

		margin-top: 50px;
	}

	.form {
		display: flex;
		flex-direction: column;
		align-items: center;
	}

	input[type=text],input[type=password],input[type=file],select {
		margin: 10px;
		padding: 10px;
		width: 500px;
		border-radius: 5px;
		border: 1px solid #ccc;
	}

	input[type=submit] {
		background-color: #4CAF50;
		color: white;
		border: none;
		padding: 10px 20px;
		text-align: center;
		text-decoration: none;
		display: inline-block;
		font-size: 16px;
		margin: 10px;
		border-radius: 5px;
		cursor: pointer;
	}

	label {
		margin: 10px;
	}

	.signup {
		text-align: center;
	}
</style>

{% endblock %}



{% block content %}

<div style="text-align: start;"><a href="{% url 'admin_app:slot' %}">Go Back</a></div>

<div class="container-fluid form">
	<div class="" style="text-align: center; margin-top: 20px; margin-bottom: 20px;">
		<h3>ADD Slots</h3>
	</div>
	<table>
		{{ msg }}



		<form action="" method="POST" enctype="multipart/form-data">
			{% csrf_token %}

			<tr>
				<td><label for="name">Name :</label></td>
				<td>Dr {{doctor.name |title}}</td>
				 
			</tr>

			<tr>
				<td><label for="day">Day :</label></td>
				<td><select name="day" id="day">
					<option value="" disabled selected>Select Day</option>
					<option value="monday">Monday</option>
					<option value="tuesday">Tuesday</option>
					<option value="wednesday">Wednesday</option>
					<option value="Thursday">Thursday</option>
					<option value="friday">Friday</option>
					<option value="saturday">Saturday</option>
					<option value="sunday">Sunday</option>



				</select></td>
			</tr>

            <tr>
                <td><label for="time">From Time :</label></td>
                <td><input type="text" name="from_time"></td>
            </tr>
            <tr>
                <td><label for="time">To Time :</label></td>
                <td><input type="text" name="to_time"></td>
            </tr>

            <tr>
				<td></td>
				<td><input type="submit" value="Submit"></td>
			</tr>

		</form>
	</table>
</div>


{% endblock %}

admin_app/templates/admin_app/staffs.html
{% extends "admin_app/admin_master.html" %}
{% load static %}
{% block header %}
<style>



</style>

{% endblock %}



{% block content %}

<div class="container-fluid admin-cards ">

    <a href="{% url 'admin_app:staff_register' %}">
        <div class="card mb-3" style="max-width: 340px; max-height:200px;">
            <div class="row g-0">
              <div class="col-md-4">
                <img src="https://cdn-icons-png.flaticon.com/512/3456/3456388.png" class="img-fluid rounded-start" alt="..."
                  width="350px">
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <h2 class="card-title">Register Staffs</h2>
                  <h3></h3>
                  <h6></h6>
                </div>
              </div>
            </div>
          </div>
    </a>
  
    <a href="{% url 'admin_app:staff_rec' %}">

      <div class="card mb-3" style="max-width: 340px; max-height:200px; ">
        <div class="row g-0">
          <div class="col-md-4">
            <img src="{% static 'image/staff.png' %}" class="img-fluid rounded-start" alt="...">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h2 class="card-title">Staff Records</h2>
              <h3></h3>
    
            </div>
          </div>
        </div>
      </div>

    </a>
  
  
  
    <div class="card mb-3" style="max-width: 340px; max-height:200px;">
      <div class="row g-0">
        <div class="col-md-4">
          <img
            src="https://cdn-icons-png.flaticon.com/512/166/166256.png"
            class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h2 class="card-title">Update Profile</h2>
            <h3></h3>
  
          </div>
        </div>
      </div>
    </div>
  
  
  </div>

{% endblock %}

admin_app/templates/admin_app/view_slots.html
{% extends "admin_app/admin_master.html" %}
{% load static %}
{% block header %}
<style>
    table {
      width: 100%;
      border-collapse: collapse;
  
    }
  
    th,
    td {
  
      padding: 8px;
      text-align: left;
      border-bottom: 1px solid #ddd;
    }
  
    th {
      background-color: #f2f2f2;
    }
  
  
    .doc-rec {
      padding-top: 50px;
    }
  
    input[type=text],
    input[type=password],
    input[type=file],
    input[type=date],
    input[type=number],
    select {
      margin: 10px;
      padding: 10px;
      width: 80px;
      border-radius: 5px;
      border: 1px solid #ccc;
    }
    button{
      
      display: inline-block;
      outline: 0;
      border: none;
      cursor: pointer;
      font-weight: 600;
      border-radius: 4px;
      font-size: 13px;
      height: 30px;
      background-color: #0000000d;
      color: #0e0e10;
      padding: 0 20px;
      
  
    }
    .table-section{
        display: flex;
        flex-direction: column;
        flex-wrap: wrap ;
        padding: 4rem 0 0;
         
    }
    
  </style>
  
  {% endblock %}
  
  
  
  {% block content %}
  
  
<section  class="table-section">
  <div class="mb-3">
    <table>
      <tr>
        <th>Name :</th>
  
        <td>{{doctor.name |title}}</td>
        <th>ID :</th>
        <td>{{doctor.doctorid}}</td>
      </tr>
      <tr>
        <th>Status</th>
        <td>{{doctor.status |title}}</td>
        <th>Add Slot :</th>
        <td><a href="{% url 'admin_app:slot_managment' doctor.id %}">Add</a></td>
        
      </tr>
    </table>
  </div>
  <div class="mb-3">
    <table>
        <tr>
            <td><h6>Day</h6></td>
            <td><h6>Time</h6></td>
            <td><h6>Add Slot</h6></td>
            <td><h6>Delete Slot</h6></td>

        </tr>
        {% for i in slot %}
        <tr>
            <td>{{i.day |title}}</td>
            <td>{{i.time}}</td>
            <td></td>
            <td><a href="{% url 'admin_app:delete_slot' i.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>
  </div>
</section>


{% endblock %}