myhospital/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myhospital_app.urls')),
    path('admin_app/',include('admin_app.urls')),
    path('doctor/',include('doctor.urls')),
    path('staff/',include('staff.urls')),
    path('patient/',include('patient.urls')),
    
    
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

patient/urls.py
from django.urls import path
from .import views
 

app_name='patient'

urlpatterns =[
    path('master',views.master,name='master'),
    path('home',views.home,name='home'),
    path('appoinments',views.appoinments,name='appoinments'),
    path('logout',views.logout,name='logout'),
    path('new/booking',views.new_booking,name='new_booking'),
    path('appoinment/list',views.appoinment_list,name='appoinment_list'),
    path('change/password',views.change_password,name='change_password'),
    path('prescriptions',views.prescriptions,name='prescriptions'),
    path('view/prescriptions/<int:bid>',views.view_prescription,name='view_prescriptions'),
    
    
    
    
    ]

staff/urls.py
from django.urls import path
from .import views

app_name='staff'

urlpatterns =[
    path('master',views.master,name='master'),
    path('home',views.home,name='home'),
    path('patients',views.patients,name='patients'),
    path('appoinments',views.appoinments,name='appoinments'),
    path('logout',views.logout,name='logout'),
    
    
    
    
    
]

patient/models.py
from django.db import models
from doctor .models import Doctor

# Create your models here.


class Slots(models.Model):
    doctor = models.ForeignKey(Doctor,on_delete=models.CASCADE)
    day = models.CharField(max_length=20)
    time = models.CharField(max_length=20)
    status = models.CharField(max_length=20,default='available')
    
    class Meta:
        db_table = 'slots_tb'

patient/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse
from django.conf import settings
from django.core.mail import send_mail
from django.core.exceptions import ValidationError  

from myhospital_app .models import Booking , Patient
from admin_app .models import Departments
from doctor.models import Doctor
from .models import Slots

# Create your views here.

def master(request):
    # patient = Patient.objects.filter(id = request.session['patient']).values('name')
    
    patient = Patient.objects.get(id = request.session['patient'])
     
    return render(request,'patient/master.html' , {'patient':patient})

def home(request):
    patient = Patient.objects.get(id = request.session['patient'])

    patient_id = request.session['patient']
    
     
    
    recent_booking = Booking.objects.filter(patient_id=patient_id).order_by('-id')[0:1]
    
    return render(request,'patient/home.html',{'booking':recent_booking,'patient':patient})

 

def appoinments(request):
    patient = Patient.objects.get(id = request.session['patient'])
    
    return render(request,'patient/appoinments.html',{'patient':patient})

def logout(request):
    del request.session['patient']
    request.session.flush()
    return redirect( 'myhospital_app:home')

 
def new_booking(request):
    patient = Patient.objects.get(id = request.session['patient'])
    doctor = Doctor.objects.all()
    departments = Departments.objects.all()
    slots = Slots.objects.all()
    msg = ''
    mail=''
    if request.method =='POST':
        patient_name = request.POST['name']
        patient_age = request.POST['age']
        gender = request.POST['gender']
        phone = request.POST['phone']
        email = request.POST['email']
        selected_department = request.POST['department']
        selected_doctor = request.POST['doctor']
        slot_day = request.POST['day-select']
        slot_time = request.POST['time-select']
        patientId = request.POST['patientId']
        
        booking = Booking(
            name = patient_name,
            age = patient_age,
            gender = gender,
            phone = phone,
            email = email,
            department_id = selected_department,
            doctor_id = selected_doctor,
            slot_id = slot_day,
            slotTime = slot_time,
            patient_id=patientId,
             
        )
        booking.save() 
        msg='Appoinment registered succesfully'
        mail='Your Appoinment for the day '+str(slot_day)+ ' in MyHospital with '+selected_doctor+' at '+str(slot_time)+  ' has been Registered Successfully'
        msg ='Registered Successfully'
        send_mail(
            'Welcome to MyHospital ' ,
            mail,
            settings.EMAIL_HOST_USER,
            [booking.email]
        )
        
    else:
        msg='Appoinment Not done'
        
    return render(request,'patient/new_booking.html',{'doctor':doctor,'departments':departments,'slots':slots,'patient':patient})
 
 
 
def appoinment_list(request):
    # getting the logged in patients id 
    
    patient_id = request.session['patient']
    
    bookings = Booking.objects.filter(patient_id=patient_id)
     
    return render(request,'patient/appoinment_list.html',{'bookings':bookings})

def change_password(request):
    msg = ''
    if request.method == 'POST':
        current_password = request.POST['current_password']
        new_password = request.POST['new_password']
        confirm_password = request.POST['confirm_password']

        if new_password == confirm_password:
            
            if len(new_password) >= 8:


                patient = Patient.objects.get(id= request.session['patient'])

                if patient.password == current_password:

                    Patient.objects.filter(id= request.session['patient']).update(password = confirm_password)
                    
                    msg = 'Password changed succesfully'
                else:
                    msg = 'Invalid password'
            else:
                msg = 'password should be min 8 characters'
        else:
            msg = 'password does not match'

    return render(request,'patient/change_password.html',{'msg':msg})


def prescriptions(request):
    patient_id= request.session['patient']
    bookings = Booking.objects.filter(patient_id=patient_id)
    
    return render(request,'patient/prescriptions.html',{'booking':bookings})

def view_prescription(request,bid):
    booking = Booking.objects.get(id = bid)
    
    return redirect('patient:appoinment_list')

patient/templates/patient/appoinment_list.html
{% extends "patient/master.html" %}
{% load static %}
{% block header %}
<style>
    table {
        width: 100%;
        border-collapse: collapse;
        
      }
      
      th, td {
         
        padding: 8px;
        text-align: left;
        border-bottom: 1px solid #ddd;
      }
      
      th {
        background-color: #f2f2f2;
      }
      
      tr:hover {
        background-color: #f5f5f5;
      }
      .doc-rec{
        padding-top: 50px;
      }

</style>

{% endblock %}



{% block content %}

 
<div class="container-fluid doc-rec">
    

    <table>
        <tr>
          
          <th>Doctor</th>
          <th>Department</th>
          <th>Appoinment Date</th>
          <th>Appoinment Time</th>
          <th>Status</th>
          <th>Prescription</th>

          
        </tr>
        {% for i in bookings %} 
        <tr>
           
          <td>{{i.doctor.name}}</td>
          <td>{{i.department.name}}</td>
          <td>{{i.slot.day}}</td>
          <td>{{i.slot.time}}</td>
          <td>{{i.status}}</td>
          <td><a href="{% url 'patient:prescriptions' %}">prescriptions</a></td>
           
           
    
        </tr>
        {% endfor %}
         
      </table>
    </div>
    
 

{% endblock %}

patient/templates/patient/appoinments.html
{% extends "patient/master.html" %}
{% load static %}
{% block header %}
<style>
 @import url('https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,100;0,300;1,200&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;1,100;1,200;1,300;1,400&display=swap');

    .main {
        width: 100%;
        padding: 20px 5%;
    }

    .patient-cards {
        width: 100%;
        height: 200px;
        display: flex;
        justify-content: space-evenly;
        text-align: center;
        align-items: center;
         
        font-family: 'Poppins', sans-serif;

    }
    .card{
        width: 300px;
        height: 120px;
        display: flex;
        flex-direction: row;
    }
    .card-text{
        width: 70%;
        height: 100%;
        overflow: hidden;
        display: flex;
        justify-content: center;
        text-align: center;
        align-items: center;
      
        
    }
    .card-image{
        width: 30%;
        height: 100%;
        overflow: hidden;
        display: flex;
        justify-content: center;
        text-align: center;
        align-items: center;
        
    }
</style>


{% endblock %}



{% block content %}

<section class="main">
    <div class="patient-cards">
        <a href="{% url 'patient:new_booking' %}">
         <div class="card cards">
            <div class="card-image">
                <i class="las la-plus-circle" style="font-size: 60px;"></i>
            </div>
            <div class="card-text">
                <h3>New Appoinment</h3>
            </div>
         </div>
         </a>
         <a href="{% url 'patient:appoinment_list' %}">
         <div class="card cards">
            <div class="card-image">
                <i class="las la-tasks" style="font-size: 60px;"></i>
            </div>
            <div class="card-text">
                <h3>Appoinments</h3>
            </div>
         </div>
         </a>

           
    </div>
</section>
{% endblock %}

patient/templates/patient/change_password.html
{% extends "patient/master.html" %}
{% load static %}
{% block header %}
<style>
	form {
		display: flex;
		flex-direction: column;
		align-items: center;

		margin-top: 50px;
	}

	.form {
		display: flex;
		flex-direction: column;
		align-items: center;
	}

	input[type=text],input[type=password],input[type=file],select {
		margin: 10px;
		padding: 10px;
		width: 500px;
		border-radius: 5px;
		border: 1px solid #ccc;
	}

	input[type=submit] {
		background-color: #4CAF50;
		color: white;
		border: none;
		padding: 10px 20px;
		text-align: center;
		text-decoration: none;
		display: inline-block;
		font-size: 16px;
		margin: 10px;
		border-radius: 5px;
		cursor: pointer;
	}

	label {
		margin: 10px;
	}

	.signup {
		text-align: center;
	}

</style>


{% endblock %}



{% block content %}



<div class="container-fluid form">
	<div class="" style="text-align: center; margin-top: 20px; margin-bottom: 20px;">
		<h3>Change Password</h3>
	</div>
	<table>
		{{ msg }}



		<form action="" method="POST" enctype="multipart/form-data">
			{% csrf_token %}

			<tr>
				<td><label for="old_password">Current Password :</label></td>
				<td><input type="text" id="old_password" name="current_password" required></td>
			</tr>

			<tr>
				<td><label for="new password">New Password :</label></td>
				<td><input type="password" name="new_password" required></td>
			</tr>

            <tr>
				<td><label for="Confirm Password">Confirm Password :</label></td>
				<td><input type="password" name="confirm_password" required></td>

			</tr>
            <tr>
				<td></td>
				<td><input type="submit" value="Submit"></td>
			</tr>

        </form>
    </table>
</div>

{% endblock %}

patient/templates/patient/home.html
{% extends "patient/master.html" %}
{% load static %}
{% block header %}
<link rel="stylesheet" href="{% static 'css/homepage.css' %}">


{% endblock %}



{% block content %}

<section class="main-section">


    <div class="profile-section">
        <div class="top-section">
            
            <div class="profile-details">
                <h3>{{patient.name |title}}</h3>
                <h4>Age :{{patient.age}}</h4>
            </div>
            <div class="profile-image">
                <img src="{% static 'image/doctor.png' %}" alt="" width="70%">
            </div>
        </div>

        <div class="bottom-section">

            <table>
                <tr>
                    <td>
                        <h5>Mobile :</h5>
                    </td>
                    <td>
                        <h5>{{patient.phone}}</h5>
                    </td>
                </tr>
                <tr>
                    <td>
                        <h5>Adress :</h5>
                    </td>
                    <td>
                        <h5>{{patient.place|title}}</h5>
                    </td>

                </tr>
                <tr>
                    <td>
                        <h5>DOB :</h5>
                    </td>
                    <td>
                        <h5>{{patient.dob}}</h5>
                    </td>
                </tr>
                <tr>
                    <td>
                        <h5>Gender :</h5>
                    </td>
                    <td>
                        <h5>{{patient.gender |title}}</h5>
                    </td>
                </tr>
                <tr>
                    <td>
                        <h5>Email :</h5>
                    </td>
                    <td>
                        <h5>{{patient.email}}</h5>
                    </td>
                </tr>
            </table>

            <div class="bottom-child">

            </div>


        </div>
    </div>


    <div class="info-section">

        <div class="top-info">
            <div><h3>Recent Booking</h3></div>
            <table>
                {% for i in booking %}
                <tr>
                    <th>Doctor :</th>
                    <td>{{i.doctor.name}}</td>
                </tr>
                <tr>
                    <th>Department :</th>
                    <td>{{i.department.name}}</td>

                </tr>
                <tr>
                    <th>Day :</th>
                    <td>{{i.slot.day}}</td>

                </tr>
                <tr>
                    <th>Time :</th>
                    <td>{{i.slot.time}}</td>

                </tr>
                <tr>
                    <th>Status :</th>
                    <td>{{i.patient.status}}</td>

                </tr>
                
                 
                {% endfor %}
            </table>

             

        </div>
         

        

    </div>

</section>












{% endblock %}

patient/templates/patient/master.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css">

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>

  <link rel="stylesheet" href="{% static 'css/masterpage.css' %}">

  <link rel="stylesheet"
    href="https://maxst.icons8.com/vue-static/landings/line-awesome/font-awesome-line-awesome/css/all.min.css">

  <link rel="stylesheet"
    href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">

  {% block header %}

  {% endblock %}
</head>


<body>
  <div class="container-fluid maindiv">

    <!-- header  -->

    <div class="row container-fluid">
      <div class="col-sm-2 dashboard1">
        <div class=" "><img src="{% static 'image/admin-logo.png' %}" alt="" width="60px" class="profile">
        </div>
        

      </div>


      <div class="col-sm-10 navbarr">

        <a href="">
          <div class="nav-items"></div>
        </a>


        <div class="nav-items " data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@mdo"><img
            src="{{patient.image.url}}" alt="" width="60px" class=""></div>

      </div>
    </div>


    <div class="row container-fluid">
      <div class=" col-sm-2 dashboard2">

        <div class="" style="color: white;"><h4>{{patient.name}}</h4></div>

        <a href="">
          <div class="dash1 "><i class="las la-igloo">Dashboard</i></div>
        </a>
        <a href="{% url 'patient:home' %}">
          <div class="dash-elements"><i class="las la-user-injured">Profile</i></div>
        </a>
        <a href="{% url 'patient:appoinments' %}">
          <div class="dash-elements"> <i class="las la-calendar-check">Appoinments</i></div>
        </a>
        <a href="{% url 'patient:change_password' %}">
          <div class="dash-elements"> <i class="las la-calendar-check">Change Password</i></div>
        </a>
         
         
        <div class="logout"><a href="{% url 'patient:logout' %}"><button type="button" class="btn btn-danger"> logout</button></a></div>



      </div>











      <div class="col-sm-10 content">
        {% block content %}


        {% endblock %}

      </div>
    </div>
  </div>


</body>

</html>

patient/templates/patient/new_booking.html
{% extends "patient/master.html" %}
{% load static %}
{% block header %}
<style>
	form {
		display: flex;
		flex-direction: column;
		align-items: center;

		margin-top: 50px;
	}
	.main{
		width: 100%;
		padding: 25px 8%;
		 
	}

	.form {
		display: flex;
		flex-direction: column;
		align-items: center;
		border-radius: 10px;
		/*border: 1px solid rgba(0, 0, 0, 0.175);*/
		
		 
	}

	input[type=text],
	input[type=password],
	input[type=file],
	input[type=date],
	select {
		margin: 10px;
		padding: 10px;
		width: 500px;
		border-radius: 5px;
		border: 1px solid #ccc;
	}

	input[type=submit] {
		background-color: #4CAF50;
		color: white;
		border: none;
		padding: 10px 20px;
		text-align: center;
		text-decoration: none;
		display: inline-block;
		font-size: 16px;
		margin: 10px;
		border-radius: 5px;
		cursor: pointer;
	}

	label {
		margin: 10px;
	}

	 
	.submitTr{
		width: 100%;
		text-align: center;
	}
	 
</style>

{% endblock %}



{% block content %}
<section class="main">

<div class="container-fluid form">
	<div class="" style="text-align: center; margin-top: 20px; margin-bottom: 20px; font-family:fantasy">
		<h2>Make an Appoinment</h2>
	</div>
	<form action="" method="POST" enctype="multipart/form-data">
	<table>
		{{ msg }}



		
			{% csrf_token %}

			<tr>
				<td><label for="name">Name:</label></td>
				<td><input type="text" id="name" name="name" value="{{patient.name}}" readonly></td>
				<td></td>
				<td><input type="text" hidden value="{{patient.id}}" name="patientId"></td>
			</tr>

			<tr>
				<td><label for="age">Age:</label></td>
				<td><input type="text" name="age" value="{{patient.age}}" readonly></td>

				<td><label for="gender">Gender:</label></td>
				<td>
                <input type="text" name="gender" value="{{patient.gender}}" readonly>
				</td>
			</tr>
			 
			 
			 

			<tr>
				<td><label for="phone">Phone No:</label></td>
				<td><input type="text" name="phone" value="{{patient.phone}}" readonly></td>

				<td><label for="email">Email:</label></td>
				<td><input type="text" name="email" value="{{patient.email}}"  readonly></td>
			</tr>


			 

			<tr>
				<td><label for="">Department:</label></td>
				<td>
					<select name="department" id="department-select">
						<option value="" selected disabled>Select a Department</option>
						{% for i in departments %}
						<option value="{{i.id}}">{{i.name}}</option>
						{% endfor %}
					</select>
				</td>

				<td><label for="date">Date:</label></td>
				<td> <select name="day-select" id="day-select">
					<option value="" disabled selected>Select Date</option>
						{% for i in slots %}
						
						<option value="{{i.id}}">{{i.day}}</option>
						{% endfor %}
				</select></td>
				
			</tr>
			 
			<tr>
				<td><label for="doctor">Doctor:</label></td>
				<td>
					<select name="doctor" id="doctor-select">
						<option value="" disabled selected>Select Doctor</option>
						{% for i in doctor %}
						
						<option value="{{i.id}}">{{i.name}}</option>
						{% endfor %}
					</select>
				</td>


				

				<td><label for="time">Time:</label></td>
				<td><select name="time-select" id="time-select">
					<option value="" disabled selected>Select Time</option>
						{% for i in slots %}
						
						<option value="{{i.id}}">{{i.time}}</option>
						{% endfor %}
				</select></td>
			</tr>

			 



			 

		
	</table>
				
	<div class="submitTr"> <td><input type="submit" value="Submit"></td></div>
	</form>
</div>
</section>


 
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

 
	<script>
		$(document).ready(function() {
			$('#department-select').on('change', function() {
				let departmentId = $(this).val();
				$.ajax({
					url: '/get_doctors/',
					data: { department_id: departmentId },
					dataType: 'json',
					success: function(data) {
						let doctorSelect = $('#doctor-select');
						doctorSelect.empty();
						doctorSelect.append($('<option>').text("select"));
						$.each(data, function(index, doctor) {
							doctorSelect.append($('<option>').text(doctor.name).attr('value', doctor.id));
						});
					}
				});
			});
        
		
			$('#doctor-select').change(function () {
				let doctorId = $(this).val();
				$.ajax({
					url: '/get_day/',
					data: { doctor_id: doctorId },
					dataType: 'json',
					success: function (data) {
						console.log(data);
						let daySelect = $('#day-select');
						daySelect.empty();
						daySelect.append($('<option>').text("select"));
						$.each(data, function (index, slot) {
							console.log(slot)
							daySelect.append($('<option>').text(slot.day).attr('value', slot.id));
						});
					}
				});
			});


			$('#day-select').change(function () {
				let slotId = $(this).val();
				$.ajax({
					url: '/get_time/',
					data: { slots_id: slotId },
					dataType: 'json',
					success: function (data) {
						console.log(data);
						let timeSelect = $('#time-select');
						timeSelect.empty();
						timeSelect.append($('<option>').text("select"));
						$.each(data, function (index, slot) {
							console.log(slot)
							timeSelect.append($('<option>').text(slot.time).attr('value', slot.id));
						});
					}
				});
			});

		});
	</script>
 

 
  



< {% endblock %}

patient/templates/patient/prescriptions.html
{% extends "patient/master.html" %}
{% load static %}
{% block header %}
<style>
  table {
    width: 100%;
    border-collapse: collapse;

  }

  th,
  td {

    padding: 8px;
    text-align: left;
    border-bottom: 1px solid #ddd;
  }

  th {
    background-color: #f2f2f2;
  }


  .doc-rec {
    padding-top: 50px;
  }

  .report,
  .medicine {
    width: 500px;
    height: 100px;
    border: black 1px;
    display: flex;

  }
</style>

{% endblock %}



{% block content %}



<div class="mb-3">
  <table>
    <tr>
      <th>Name :</th>

      <td>{{booking.name}}</td>
      <th>Age :</th>
      <td></td>
    </tr>
    <tr>
      <th>DOB :</th>
      <td></td>
      <th>Place</th>
      <td> </td>
    </tr>
  </table>
</div>
<form action="" method="POST">
  {% csrf_token %}

  <div class="mb-3 report">
    <h6>Report :</h6>  
  </div>
  <div class="mb-3 medicine">
    <h6>Medicine :</h6>  
  </div>
   
</form>
{% endblock %}